#!/bin/bash -x

usage(){
    cat <<EOH

    Usage:

    $0 -i <input dir> [ -o <output dir> ]
    $0 -f <input file> [ -o <output dir> ]

    Transcodes video files to ProRes 422 (video) and pcm_s16be (audio)
    *.mov files are ignored.

EOH
}

fail_usage(){
    if [ "$1" ]; then echo "$1"; fi
    usage && exit 1
}

transcode(){
    INFILE="$1"
    OUTFILE="$2"
    
    test -d "$(dirname $OUTFILE)" || fail_usage

    ffmpeg -nostdin -i "$INFILE" -c:v prores -profile:v 2 -c:a pcm_s16be -framerate 30 "$OUTFILE"
}

while getopts ":i:o:f:" opt; do
    case ${opt} in
        i ) INDIR=$OPTARG
            test -d "$INDIR" || fail_usage "Directory $INDIR does not exist"
            ;;
        o ) OUTDIR=$OPTARG
            test -d "$OUTDIR" || fail_usage "Directory $OUTDIR does not exist"
            ;;
        f ) INFILE=$OPTARG
            test -r "$INFILE" || fail_usage "Cannot read $INFILE"
            ;;
        h) usage && exit 0
            ;;
        \? ) fail_usage
            ;;
    esac
done

shift $(( OPTIND-1 ))

if [ ! "$INDIR" ]; then
    INDIR=$(pwd)
fi

if [ ! "$OUTDIR" ]; then
    OUTDIR=$(pwd)
fi

if [ "$INFILE" ]; then
    OUTFILE=$(basename $INFILE)
    OUTFILE="${OUTDIR}/${OUTFILE%.*}.mov"
    transcode "$INFILE" "$OUTFILE"
    exit 0;
fi

ls -F "$INDIR" | grep -P "\w$" | grep -v ".mov$" | while read F; do
    OUTFILE="${OUTDIR}/${F%.*}.mov"
    transcode "${INDIR}/${F}" "$OUTFILE"
done
